.eslintrc.cjs, app/root.tsx, app/routes/products.$categorySlug/route.tsx, src/components/category-link/category-link.tsx, src/components/footer/footer.tsx, src/components/header/header.tsx
1. Component CategoryLink: prop `title` removed, `children` added.
2. Footer: social network links updated.
=> fixes: move title to children in CategoryLink, update URLs in footer links to social networks

_codux/boards/error-component/error-component.board.tsx, app/root.tsx, src/components/error-component/error-component.module.scss, src/components/error-component/error-component.tsx, src/components/site-wrapper/site-wrapper.module.scss, src/utils/common.ts
* adds error component
* adds ErrorBoundary to a `root` route 
https://github.com/user-attachments/assets/b32b33d7-5897-4308-9f4f-7106362248b1
=> feat: add root error boundary

src/components/error-component/error-component.module.scss, src/components/site-wrapper/site-wrapper.module.scss
=> fix: home page styles

app/routes/about-us/about-us.module.scss, app/routes/about-us/route.tsx
=> feat: about page

app/routes/product-details.$productSlug/product-details.module.scss, src/styles/common.scss, src/styles/general.scss, vite.config.ts
https://github.com/user-attachments/assets/0947a861-0542-4cea-a410-32671a0eb5e9
- make `vite.config.ts` the same as in [e-commerce-remix](https://github.com/codux-templates/e-commerce-remix/blob/9dddba82ed017bb7e8020390fca1ab5d1cc00625/vite.config.ts)
- p.s. oveflow hidden is applied for header and footer in video
=> feat: responsive product page

src/components/cart/cart-item/cart-item.module.scss, src/components/drawer/drawer.module.scss
Not much, just make drawer responsive to handle viewport width less than 420px.
=> feat: responsive cart

app/routes/refund-policy/refund-policy.module.scss, app/routes/refund-policy/route.tsx
Adds 'Refund Policy' page
_____
=> feat: add refund policy page

app/routes/_index/index.module.scss, app/routes/_index/route.tsx, src/components/label-with-arrow/label-with-arrow.module.scss, src/components/label-with-arrow/label-with-arrow.tsx
`<LabelWithArrow>` component:
* Fixed hover animation (didn't animate correctly on mouseleave)
* Removed fixed width, now the component adjusts to the amount of text.
=> fix: styling for LabelWithArrow

app/routes/privacy-policy/route.tsx, app/routes/refund-policy/route.tsx, app/routes/shipping-policy/route.tsx, app/routes/terms-and-conditions/route.tsx, src/styles/common.scss
Implemented pages:
* Terms & Conditions
* Privacy Policy
* Shipping Policy
* Refund Policy
I didn't replicate the styling precisely, because in the original template the font size of the heading jumps three times as you shrink the window, it looks kinda weird at some sizes.
I've also limited the max width of the text to keep it readable at wide window sizes, it allowed to simplify styling a little.
Looks good enough:
=> feat: add all static pages

src/components/order-summary/order-item/order-item.module.scss, src/components/order-summary/order-item/order-item.tsx, src/components/order-summary/order-summary.module.scss
Change layout for mobile view.
https://github.com/user-attachments/assets/6246500b-7685-4953-8713-d05fbfe90957
=> feat: responsive thank you page

app/routes/products.$categorySlug/products.module.scss, app/routes/products.$categorySlug/route.tsx
https://github.com/user-attachments/assets/e0fac5b8-7a4f-4414-8695-0872b526cc9c
- Hide categories navigation on small viewports
- I can't find the exact animation duration so I set the duration that feels the most accurate to me.
=> feat: make products category page responsive + add product card animation

app/routes/product-details.$productSlug/route.tsx, app/routes/products.$categorySlug/route.tsx, app/routes/thank-you/route.tsx, src/api/api-hooks.ts, src/api/ecom-api-context-provider.tsx, src/api/ecom-api.ts, src/api/types.ts, src/components/cart/cart.tsx, src/components/featured-products-section/featured-products-section.tsx, src/utils/index.ts
Improved error handling according to latest changes in `e-commerce-remix` template.
*  Add specific per page error handling with ErrorBoundary
=> feat: per page error handling

app/routes/about-us/route.tsx
Adds animations for `About Us` page
https://github.com/user-attachments/assets/a1111fde-69b4-40df-98ee-d4fb63b4553d
=> feat: abous us page animations

_codux/boards/visual-effects/visual-effects.board.tsx
=> feat: update example image on the visual effects board

_codux/ui-kit/buttons/ui-kit-buttons.board.tsx, src/components/icons/index.ts, src/components/icons/whatsapp-icon.tsx, src/components/share-product-links/share-product-links.tsx, src/styles/common.scss
- Added variants for buttons
- Added common class for small icons
- Added social media icons to UI kit
=> feat: add button variants and social icons to the UI Kit

_codux/boards/link-cards.board.tsx, _codux/boards/text-banner.board.tsx
=> feat: boards for text banner and link cards

src/api/constants.ts, src/api/ecom-api.ts
Porting https://github.com/codux-templates/e-commerce-remix/pull/56 over to this repo. I have no idea what I'm doing.
=> fix: reinitialize session on wix client id change

.github/workflows/node.js.yml, _codux/ui-kit/typography/typography.board.module.scss, app/routes/_index/index.module.scss, package.json, src/components/header/header.module.scss, src/components/icons/cart-icon/cart-icon.module.scss, src/styles/colors.scss, src/styles/reset.scss
* adds pretest job that performs linting and type checking of commits and pull requests
* fixes all type/lint issues
=> feat: adds pretest job

app/routes/thank-you/route.tsx, app/routes/thank-you/thank-you.module.scss
=> fix: show thank you page even if orderID is missing

src/components/featured-products-section/featured-products-section.module.scss, src/styles/common.scss
https://github.com/user-attachments/assets/7689fa06-a79b-45ee-ba6c-166cbfa70d3d
=> UI: responsive featured products on the home page

app/routes/_index/route.tsx
`kitchen` was incorrect category slug.
=> fix: kitchen category slug

app/routes/product-details.$productSlug/route.tsx, app/routes/products.$categorySlug/route.tsx, src/components/cart/cart-item/cart-item.module.scss, src/components/cart/cart-item/cart-item.tsx, src/components/icons/error-icon.tsx, src/components/icons/index.ts, src/components/product-card/product-card.module.scss, src/components/product-card/product-card.tsx, src/components/quantity-input/quantity-input.module.scss, src/components/quantity-input/quantity-input.tsx, src/styles/common.scss
Show product out of stock indication. I don't handle out of stock variants.
=> feat: show out of stock indication

package-lock.json, package.json
Proof that Codux Online works:
https://web.codux.com/?boardPath=%2F_codux%2Fboards%2Fvisual-effects%2Fvisual-effects.board.tsx&isNewComponent=false&type=board&workspaceId=333fd678-e3c0-4190-866d-30f20fc2b564
=> fix: add @emotion/is-prop-valid to deps as a workaround for codux online

_codux/boards/range-slider/range-slider.board.module.scss, _codux/boards/range-slider/range-slider.board.tsx, src/components/range-slider/range-slider.module.scss, src/components/range-slider/range-slider.tsx
https://github.com/user-attachments/assets/3dbde6e3-946b-45a3-b7f6-5720a22e5de4
=> feat: add RangeSlider component

src/components/range-slider/range-slider.tsx
Fixes after review https://github.com/codux-templates/e-commerce-reclaim/pull/114
=> fix: RangeSlider fixes

_codux/boards/range-slider/range-slider.board.tsx, src/components/range-slider/range-slider.module.scss, src/components/range-slider/range-slider.tsx, src/styles/common.scss
https://github.com/codux-templates/e-commerce-reclaim/pull/115#pullrequestreview-2340183264
=> refactor: improve RangeSlider customization

_codux/ui-kit/buttons/buttons.board.tsx, app/routes/cart/route.module.scss, app/routes/cart/route.tsx, src/components/cart/cart-item/cart-item.module.scss, src/components/cart/cart.module.scss, src/router/config.ts, src/styles/common.scss
https://github.com/user-attachments/assets/d5f78635-04f5-42a0-9cc2-7b97b2e64755
=> feat: create cart page markup and styles

src/components/cart/cart-item/cart-item.module.scss, src/components/drawer/drawer.module.scss, src/components/footer/footer.module.scss, src/components/header/header.module.scss, src/components/product-card/product-card.module.scss, src/components/product-images/product-images.module.scss, src/styles/common.scss
The background controller in Codux cannot deal with variables in the `background-color` property: https://github.com/wixplosives/codux/issues/23117
As a workaround, I've changed `background-color` to `background` across the project.
I didn't verify carefully if this has caused any regressions, but I've clicked around and things seem to be fine.
=> refactor: replace all 'background-color' with 'background'

app/routes/products.$categorySlug/route.tsx, src/api/product-filters.ts, src/components/product-filters/product-filters.tsx, src/utils/index.ts, src/utils/use-search-params-state.ts
Same as https://github.com/codux-templates/e-commerce-reclaim/pull/144 but into `development` branch.
=> refactor: product filters in URL search params

_codux/ui-kit/buttons/buttons.board.module.scss, _codux/ui-kit/buttons/buttons.board.tsx, _codux/ui-kit/components/components.board.module.scss, _codux/ui-kit/components/components.board.tsx, src/components/icons/arrow-right-icon.tsx, src/components/icons/chevron-right-icon.tsx
=> fix: move board styles out of variants

app/routes/product-details.$productSlug/route.tsx, src/hooks/use-cart.ts
This work was done before. But later reverted back. Now I need to handle errors and need to use `useCart` again.
=> fix: use useCart to add items to cart

app/routes/cart/route.module.scss, app/routes/cart/route.tsx
=> fix: add styles of empty cart for the page

src/styles/index.scss
=> fix: remove garbage styles from index.scss

app/routes/members-area.my-account/route.module.scss, app/routes/members-area.my-account/route.tsx, app/routes/members-area.my-orders/route.module.scss, app/routes/members-area.my-orders/route.tsx, app/routes/members-area/route.module.scss, app/routes/members-area/route.tsx, src/styles/common.scss
Added `members-area` page and two 'under construction' sub-pages: `members-area/my-account` and `members-area/my-orders`. These pages aren't accessible through the UI for now.
=> Add members area pages

app/routes/cart/route.tsx, lib/ecom/hooks.ts
Fixes bug described in the [comment](https://github.com/wixplosives/codux/issues/23062#issuecomment-2449631439).
=> fix: show empty cart when no cart data retrieved from the backend

app/routes/cart/route.module.scss, app/routes/cart/route.tsx, lib/ecom/hooks.ts, src/components/cart/cart.tsx
* Loading state: large spinner
* Error state: centered error message
https://github.com/user-attachments/assets/112f51d1-e8b3-4ffa-84ef-3f1718b9ad4f
=> feat: add loading and error state to the cart page

_codux/boards/dropdown-menu/dropdown-menu.board.module.scss, _codux/boards/dropdown-menu/dropdown-menu.board.tsx, package-lock.json, package.json, src/components/dropdown-menu/dropdown-menu.module.scss, src/components/dropdown-menu/dropdown-menu.tsx
add dropdown menu component. this component will be used for user/login menu
=> feat: add dropdown menu component

app/routes/members-area.my-orders/route.module.scss, app/routes/members-area.my-orders/route.tsx, app/routes/members-area/route.module.scss, lib/ecom/api.ts, lib/ecom/types.ts
=> feat: Add my orders page

_codux/boards/dialog/dialog.board.module.scss, _codux/boards/dialog/dialog.board.tsx, package-lock.json, package.json, src/components/dialog/dialog.module.scss, src/components/dialog/dialog.tsx
Added `Dialog` component based on `@radix-ui/react-dialog`.
Animation is taken from the [Radix UI example](https://www.radix-ui.com/primitives/docs/components/dialog)
https://github.com/user-attachments/assets/7530529a-0d6b-4e94-b696-682f8a57874d
=> feat: dialog component

_codux/boards/toast/toast.board.module.scss, _codux/boards/toast/toast.board.tsx, _codux/boards/toaster/toaster.board.module.scss, _codux/boards/toaster/toaster.board.tsx, app/root.tsx, package-lock.json, package.json, src/components/toast/toast.module.scss, src/components/toast/toast.tsx, src/components/toaster/toaster.tsx
Based on #158 with many tweaks.
Usage example:
```tsx
import { toast } from '~/src/components/toast/toast';
<button onClick={() => toast.success('Yay')} />;
```
https://github.com/user-attachments/assets/87e4e0fb-d99a-4c61-afde-fff2330da186
https://github.com/user-attachments/assets/9eaac944-cf25-4c95-bacd-3c0a71fb8b19
=> feat: toast notifications

app/routes/cart/route.module.scss, app/routes/cart/route.tsx
=> fix: remove shipping information from the Cart page

_codux/boards/avatar/avatar.board.module.scss, _codux/boards/avatar/avatar.board.tsx, _codux/boards/breadcrumbs.board.module.scss, _codux/boards/breadcrumbs.board.tsx, _codux/boards/cart-item/cart-item.board.tsx, _codux/boards/color-select.board.module.scss, _codux/boards/color-select.board.tsx, _codux/boards/error-page/error-page.board.tsx, _codux/ui-kit/components/components.board.tsx
Reduced dimensions of some boards to more tightly hug their content. Added a grid wrapper to some boards for centered alignment.
=> feat: make boards look nicer by tweaking their size and padding

app/routes/products.$categorySlug/route.tsx, src/components/applied-filter/applied-filter.tsx, src/components/applied-product-filters/applied-product-filters.tsx, src/components/cart/cart-view/cart-view.tsx, src/components/dialog/dialog.tsx, src/components/header/header.module.scss, src/components/header/header.tsx, src/components/icons/clear-icon.tsx, src/components/icons/cross-icon.tsx, src/components/icons/cross-small-icon.tsx, src/components/icons/index.ts, src/components/icons/search-icon.tsx, src/components/search-input/search-input.module.scss, src/components/search-input/search-input.tsx, src/components/sidebar-navigation-menu/sidebar-navigation-menu.tsx, src/components/toast/toast.tsx, src/wix/ecom/types.ts, src/wix/products/product-filters.ts
- searches product names from all products
- uses existing all-products route to show results and allow further sorting/filtering
- leverages `$contains` (no fuzzy yet), which is publicly available on the rest API. the JS API implements it, but does not expose it via the types.
- fuzzy is easily accessible in V3 API
=> feat: implement search functionality

src/wix/categories/category-details.ts, src/wix/categories/index.ts, src/wix/products/product-details.ts, src/wix/utils/media.ts
Allow to get category image like so:
```ts
const category = await api.getCategoryBySlug(categorySlug);
const url = getCategoryImageUrl(category, { minWidth: 600, minHeight: 300 });
```
=> feat: utility function for getting category image
