codux-templates/e-commerce-reclaim

- app/root.tsx
- app/routes/product-details.$productSlug/product-details.module.scss
- app/routes/product-details.$productSlug/route.tsx
- app/routes/products.$categorySlug/products.module.scss
- app/routes/products.$categorySlug/route.tsx
- src/components/breadcrumbs/breadcrumbs.module.scss
- src/components/breadcrumbs/breadcrumbs.tsx
- src/components/icons/arrow-right.tsx
- src/components/icons/index.ts
- src/components/product-link/product-link.tsx
- src/router/types.ts
Guide: https://remix.run/docs/en/main/guides/breadcrumbs.
- We don't show breadcrums on every page, only products category and product details.
- On product details we have a special case. Product details route is not nested inside category route. But we want to  show the category link in breadcrumbs if a user visits the product page directly from the category page. I do this using history state. So the category link appears only on the client side.
> feat: breadcrumbs

- src/components/drawer/drawer.tsx
I made a mistake and completely disabled scroll on all pages. The scroll should be disabled only when the drawer is open.
> fix: disable scroll only when drawer is open

- _codux/app.app-def.tsx
- app/root.tsx
- app/routes/product-details.$productSlug/route.tsx
- app/routes/products.$categorySlug/route.tsx
- codux.config.json
- package-lock.json
- package.json
Adds define app config that allows to run a template in full app mode in Codux.
https://github.com/user-attachments/assets/b9ae3843-277a-460b-9f45-b46479a22e67
`define-remix-app` wrapper runs all loaders in web workers, it means we can't use node specific login there (e.g. we can't use things from '@remix-run/node' package).
____
`define-remix-app` doesn't pass correctly an error from loader to a route component, that can lead to weird errors
https://github.com/user-attachments/assets/5e61a4d4-5812-4e2a-b527-1c3fa1c5f557
This error appears because `useLoaderData` returns an empty object instead of an error that a category doesn't exist 
At the moment, we need to use `peter/production-app` branch in Codux and run it with a command:
```bash
npm run codux:electron:release
```
> feat: run full app in codux

- README.md
Based on the [eCommerce Starter Readme](https://github.com/codux-templates/e-commerce-remix/blob/main/README.md) with some changes:
* Changed the name of the project
* Changed the list of technologies
* Changed the instructions on how to update the links after adding new categories
* Changed "The project comes with 5 board templates" to "The project comes with board templates", because the number of the templates can vary and ain't nobody got time to update the readme.
> docs: add a readme

- app/routes/_index/route.tsx
I removed `featuredProducts` class from the page scss and created `alternateBackground` class in _common.scss_ and forgot to set proper `className` to component.
> fix: set common class with alternative background

- app/routes/_index/index.module.scss
Incorrect styling of the parallax block on the home page was causing horizontal scroll.
> fix: remove horizontal scroll from the home page

- _codux/ui-kit/buttons/ui-kit-buttons.board.module.scss
- _codux/ui-kit/components/components.board.tsx
- _codux/ui-kit/typography/typography.board.module.scss
- _codux/ui-kit/typography/typography.board.tsx
- app/routes/product-details.$productSlug/product-details.module.scss
- app/routes/products.$categorySlug/products.module.scss
- src/components/order-summary/order-item/order-item.module.scss
- src/components/order-summary/order-summary.module.scss
- src/styles/common.scss
- src/styles/index.scss
- src/styles/variables.scss
* Moved viewport breakpoints to `src/styles/variables.scss`
* Removed imports of `common.scss` in TS and SCSS files other than `index.scss`
* Fixed ESLint errors in boards added by non-developers.
For some reason, Codux couldn't resolve `import './variables.scss'` in `common.scss`, so as a workaround I've imported it in `index.scss` instead. (Other imports of `variables.scss` seem to work in Codux, e.g. in `order-item.module.scss`).
> refactor: prevent duplicate imports of common.scss

- codux.config.json
Remix has some node apis that you should use in order to call some server side functions, but it is written the same place where a component file is. 
Our code doesn't know that they exist and just throws an error.
We added to Codux and Codux-Core solutions to this problem, but we need to change also the templates side:
We need to add these aliases so preview would not show error but will call our own implementations of remix node apis.
This kind of PR will show again in other remix-templates also.
> fix: add alias false to node apis

- app/routes/about-us/about-us.module.scss
Tweaks description styles to look better on different screen sizes
https://github.com/user-attachments/assets/e6d54d29-b0aa-4101-b0a8-45cc4d248e10
https://github.com/user-attachments/assets/1e90bdaa-6378-471c-b8c6-bde4785b23b9
> fix: `about us` page style tweaks

- app/routes/product-details.$productSlug/route.tsx
- app/routes/products.$categorySlug/route.tsx
An error emitted from one `ErrorBoundary` won't be caught by an `ErrorBoundary` of a parent route.
Such error will break the whole application.
All possible errors should be handled by closest ErrorBoundary in a routes hierarchy
> fix: error handling in ErrorBoundary

- src/components/error-page/error-page.module.scss
The header div was centered, but the text in the div was not. The issue was only visible with long text.
Before:
After:
> fix: center header text on the error page

- app/routes/product-details.$productSlug/route.tsx
- app/routes/products.$categorySlug/route.tsx
This reverts commit ad9195c825741164cce9e98216b6f2c070dc797b.
The assumption I described in this PR is not correct, errors emitted by nested error boundaries handled correctly.
The problem is in `getErrorMessage` function and i will fix it in next PR.
it returns an object in case when an error is `ErrorResponse`
> Revert "fix: error handling in ErrorBoundary"

- _codux/boards/breadcrumbs.board.tsx
- app/root.tsx
- app/routes/product-details.$productSlug/route.tsx
- app/routes/products.$categorySlug/route.tsx
- src/components/breadcrumbs/breadcrumbs.tsx
- src/router/types.ts
- src/router/use-breadcrumbs.ts
On the product details page the category breadcrumb is added on the client-side (based on the history state).
The hydration failed because of that.
<br /><br />
I fixed this error using `ClientOnly` component but I had to rewrite breadcrumbs a bit.
Also, I added `Breadcrumbs` board.
> fix: fix hydration failed error

- src/utils/index.ts
In case of `ErrorResponse` emitted by route loader, `getErrorMessage` function return an object instead of a string.
> fix: getErrorMessage returns an object in case of ErrorResponse

- app/routes/product-details.$productSlug/route.tsx
- app/routes/products.$categorySlug/route.tsx
- src/utils/index.ts
* Correctly extract the error message when one of the following patterns is used:
* `throw new Response('oops')`
* `throw json('oops')`
* `throw json({message: 'oops'})`
* Update function description
* Update `ErrorBoundary` for the product page and category page to use `getErrorMessage`.
> fix: improve handling of React Router's ErrorResponse in  getErrorMessage

- app/routes/product-details.$productSlug/route.tsx
To be honest I don't understand why using `json()` utility breaks it in Codux 🤷‍♂️ . `product` ends up being `undefined` on the client-side. I removed it and it fixed the problem. + We don't use it in all other route loaders. 
Before
> fix: remove json utility in product details loader

- app/routes/thank-you/route.tsx
This is a workaround for Codux, which injects an error boundary around almost every component, including the app's own error boundaries.
> feat: don't throw in error boundary on the 'thank you' page

- src/styles/common.scss
- src/styles/index.scss
Add keyboard focus for links. Previously we only had keyboard focus for buttons.
---
---
---
> fix: add keyboard focus for links and other focusable elements

- src/components/featured-products-section/featured-products-section.tsx
- src/components/product-card/product-card.module.scss
- src/components/product-card/product-card.tsx
Since the `<FeaturedProductsSection>` is loaded on the client, sometimes there's an unpleasant page jump if you scroll before this section has loaded.
I've added skeletons that normally won't be visible, you have to scroll down to the products section fast enough. I wasn't sure whether to pass dummy data into the `<ProductCard>` component, or to add a prop `skeleton={true}` or to implement a separate `<ProductCardSkeleton>`.
https://github.com/user-attachments/assets/c2d73c98-95c3-4d64-a70b-9321073f98bb
> feat: skeletons for the featured products section

- src/components/visual-effects/reveal.tsx
(The second card has keyboard focus)
---
> fix: don't clip focus outline in featured products section

- app/routes/products.$categorySlug/route.module.scss
- app/routes/products.$categorySlug/route.tsx
You can see a tiny blue square in the top left corner of the first card. That's keyboard focus outline. It doesn't cover the entire card because the `<a>` element has `display: inline`.
---
> fix: keyboard focus outline on product cards

- _codux/boards/text-banner.board.tsx
- src/styles/common.scss
1. I don't see a need to override the styling of this block for different breakpoints, it scales down nicely without any special adjustments.
2. Padding was handled inconsistently: at the desktop size, the vertical padding came from `.textBannerSection`, but at the tablet/mobile size, it switched to `.textBanner` for no apparent reason. _(In principle, we could even remove `.textBannerSection` and put its styles on the `.textBanner` instead.)_
I didn't aim for a pixel-perfect reproduction of the original template, but it's very close at both desktop and mobile sizes.
---
---
> refactor: simplify styling of the text banner

- src/components/header/header.module.scss
- src/styles/index.scss
Checked the site on my phone (375px × 812px) and the horizontal page padding (2vw) did in fact look weird. I've set the minimum at 15px.
Also noticed that the header looks wonky. Adjusted the font size at mobile breakpoint to match the original template.
Before and after:
> fix: tweak page padding and header font size on mobile

- src/components/footer/footer.module.scss
Desktop:
Tablet:
Mobile:
It is not quite the same like on the wix template, but looks good for me.
If the text of the second column is quite small then the footer has a big space in the center:
1. I can add some `padding-right` to navigation section for mobile
2. We can leave it on user. If they have narrow text there, let they add the indent. I would choose this option.
> feat: make footer responsive

- _codux/ui-kit/components/components.board.tsx
- app/routes/product-details.$productSlug/route.tsx
- app/routes/products.$categorySlug/route.tsx
- src/components/featured-products-section/featured-products-section.tsx
- src/components/product-card/product-card.tsx
- src/components/product-price/product-price.tsx
It's not convinient to work with the full `priceData` object in the props panel in Codux. It's not very clear what data should be passed to see the price in the product card, especially for designers.
It's better to have more primitive props: `price: string` and `discountedPrice: string`.
> refactor: simplify product price props

- src/components/quantity-input/quantity-input.module.scss
> fix: remove blue focus outline from quantity input

- _codux/boards/visual-effects/visual-effects.board.module.scss
- _codux/ui-kit/components/components.board.module.scss
- app/routes/product-details.$productSlug/route.module.scss
- app/routes/products.$categorySlug/route.module.scss
- src/components/cart/cart-item/cart-item.module.scss
- src/components/cart/cart.module.scss
- src/components/drawer/drawer.module.scss
- src/components/footer/footer.module.scss
- src/components/header/header.module.scss
- src/components/order-summary/order-item/order-item.module.scss
- src/components/order-summary/order-summary.module.scss
- src/components/product-card/product-card.module.scss
- src/components/quantity-input/quantity-input.module.scss
- src/components/spinner/spinner.module.scss
- src/styles/colors.scss
- src/styles/common.scss
- src/styles/index.scss
Mika wants to make it more clear that the scales `colorA` and `colorB` are the most used, and the other color scales are used more sparigly.
Here's how these two scales are named in Wix Studio:
The only "action" color used in the template is the third in the scale. Here's what it is used for:
* Browse page: `.categoryLinkActive`
* Order summary: `.note`
* Order item: `.productDetails`
* `.mutedPrimaryButton`
Hardly an "action".
So for lack of better names, I've named them primary (the most used scale), and secondary (the second most used scale).
> refactor: rename colorA to primary, colorB to secondary

- _codux/ui-kit/components/components.board.module.scss
- _codux/ui-kit/components/components.board.tsx
- src/styles/common.scss
"Components" UI Kit board:
* Removed unused CSS.
* Wrapped snippets with `<Variant>`.
* Fixed incorrect names for existing variants.
* Removed all board-specific CSS/HTML from variants.
* Added discounted price for the product card.
* Added an example of a "SALE" ribbon.
* Introduced a common class for the ribbon element.
> feat: tidy up the components ui kit and add variant wrappers

- _codux/ui-kit/buttons/buttons.board.tsx
- _codux/ui-kit/components/components.board.tsx
- _codux/ui-kit/sections/sections.board.tsx
- _codux/ui-kit/typography/typography.board.tsx
> fix: make boards as snippets to see them in 'UI Kit' boards group

- app/routes/product-details.$productSlug/route.module.scss
- app/routes/product-details.$productSlug/route.tsx
- src/components/accordion/accordion.module.scss
- src/components/accordion/accordion.tsx
I'm using `Accordion` in product filters. A range slider highlights a focused thumb with a box-shadow. Because accordion item has `overflow-y: auto` the overflowed box-shadow is cut off.
<br /><br />
Using `transition-delay` and `transition-behavior: allow-discrete`  I reset the overflow after transiton ends.
> feat: allow accordion item content to overflow when expanded

- _codux/ui-kit/animations/animations.board.tsx
- _codux/ui-kit/sections/sections.board.tsx
- app/routes/_index/route.tsx
- app/routes/about-us/route.tsx
- src/components/featured-products-section/featured-products-section.tsx
- src/components/footer/footer.tsx
Codux can't correctly detect which props of our animation components are important, and hides them behind "Display all properties (279)". As a workaround, I've passed explicit prop values instead of relying on defaults.
For reference, here are the default values for each animation component:
* `<FadeIn duration={1.8}>`
* `<FloatIn direction="up" duration={1.2} distance={120}>`
* `<Reveal direction="down" duration={1.4}>`
* `<BackgroundParallax parallaxStrength={0.75}>`
Ta-da:
> feat: set explicit prop values for animation components

- app/routes/products.$categorySlug/route.tsx
- src/components/applied-product-filters/applied-product-filters.tsx
- src/components/product-filters/product-filters.tsx
- src/components/range-slider/range-slider.tsx
1. When `min` or `max ` of `<input type="range" />` is a floating number and the step is an integer, the slider looks weird:
Plain HTML https://jsfiddle.net/v6xpecL0/
To overcome this I set `step="any"` to the price range slider.
Additionally, I round values on change, because:
1. It's not convinient to slide between decimals.
2. It's nicer to have integer in URL than `?maxPrice=11.1199717420213`
<hr />
2. Previously, applied price filter looked bad after changing only mimumum or only maximum:
<br /><br />
The fix is to show the lowest/highest value if it's not applied explicitly.
> fix: price filter fixes

- _codux/boards/color-select.board.tsx
- _codux/ui-kit/components/components.board.tsx
- src/components/color-select/color-select.module.scss
- src/components/color-select/color-select.tsx
- src/styles/common.scss
`options` is not `string[]` (unfortunately) because for products it's allowed to add colors with the same color value.
What must be unique is the name given to color. So we will use name as the color id.
> feat: color select

- app/routes/products.$categorySlug/route.tsx
- src/api/product-filters.ts
- src/api/use-product-filters.ts
- src/components/product-filters/product-filters.tsx
- src/utils/index.ts
- src/utils/use-search-params-state.ts
Add `useSearchParamsOptimistic` hook to simplify working with the state that lives in URL search params.
This will come in handy for other states in URL, such as product sorting.
> refactor: product filters in URL search params

- app/routes/product-details.$productSlug/route.module.scss
- app/routes/product-details.$productSlug/route.tsx
- package-lock.json
- package.json
- src/api/api-hooks.ts
- src/api/cart-helpers.ts
- src/api/ecom-api.ts
- src/api/types.ts
- src/components/cart/cart-item/cart-item.module.scss
- src/components/product-images/product-images.tsx
- src/components/product-option/product-option.module.scss
- src/components/product-option/product-option.tsx
- src/components/select/select.module.scss
- src/components/select/select.tsx
- src/styles/colors.scss
- src/utils/product-utils.ts
Copy product variants functionality from https://github.com/codux-templates/e-commerce-remix
The only differences are in styles and components that we use.
PR includes:
- Allow to choose product options.
- Adjust product details depending on the selected options.
- Update API to handle adding product with options to the cart.
To be done:
- Display selected options in cart. I'll do this in a separate PR https://github.com/codux-templates/e-commerce-reclaim/pull/151
- Hidden and out of stock variants. I'll wait for https://github.com/codux-templates/e-commerce-remix/pull/89
> feat: support product variants

- app/routes/product-details.$productSlug/route.tsx
- src/components/color-select/color-select.module.scss
- src/components/color-select/color-select.tsx
- src/components/product-option/product-option.tsx
- src/utils/product-utils.ts
Copy https://github.com/codux-templates/e-commerce-remix/pull/89
Differences:
- styles
- components usage
- `crossedOut` instead of `inStock` for color select option to keep `ColorSelect` component generic.
> feat: non-visible and out of stock variants

- _codux/boards/cart-item/cart-item.board.tsx
- src/components/cart/cart-item-options/cart-item-options.module.scss
- src/components/cart/cart-item-options/cart-item-options.tsx
- src/components/cart/cart-item/cart-item.module.scss
- src/components/cart/cart-item/cart-item.tsx
Show product options in cart. By default only 1 option is visible. A user can expand all of them using "More Details" button.
> feat: show product options in cart

- lib/ecom/api.ts
- lib/ecom/types.ts
When returning a failure response from Ecom API, we were sometimes discarding the error message. I've made the error message mandatory, and fixed the cases where it was discarded.
> fix(ecom-api): make error message required in ecom api failure response

- _codux/board-wrappers/component-wrapper.tsx
Render wrapped component as an error boundary of the stubbed Remix app. 
In such case if stubbed Remix app will navigate to non-existing path root ErrorBoundary will be triggered... which will render the same UI (wrapped by the `ComponentWrapper`) so the user won't notice a difference :)
> fix: Make ComponentWrapper not dependent on ROUTES object

- package-lock.json
- package.json
new version prints a warning for every transpiled file. could be seen during `npm run build/dev`
> fix(sass): revert to 1.79.x to avoid import warnings

- app/routes/_index/route.tsx
- src/components/featured-products-section/featured-products-section.tsx
If category doesn't exists, fetch data from 'all-products' category.
> fix: featured products fallback didn't work

- app/routes/product-details.$productSlug/route.tsx
- app/routes/products.$categorySlug/route.tsx
- app/routes/thank-you/route.tsx
- lib/ecom/api-context.tsx
- lib/ecom/api.ts
- lib/ecom/session.ts
We use several ways to get an instance of EcomAPI:
1. `initializeEcomApi(request)`
2. `createApi(createWixClient(tokens))`
3. `createApi(createWixClient())`
To unify them and to make it explicit when we're creating an anonymous instance that doesn't have a client token, I've changed these as follows:
1. `initializeEcomApiForRequest()`
2. `initializeEcomApiWithTokens()`
3. `initializeEcomApiAnonymous()`
Also made the function `createApi()` private.
> refactor: functions for ecom api initialization

- lib/ecom/api.ts
- lib/ecom/types.ts
Wix Ecom doesn't have a concept of promoted products, our function `api.getPromotedProducts()` simply returns 4 products from the store in unspecified order.
This function is used only in `e-commerce-remix` template, I've removed it from the API, it should be replaced with `api.getProducts({ limit: 4 })`
> refactor: remove getPromotedProducts function

- lib/ecom/api.ts
- lib/ecom/hooks.ts
- lib/ecom/types.ts
- src/components/featured-products-section/featured-products-section.tsx
Since we now have skeletons in the `<FeaturedProductsSection>`, showing them if the category doesn’t exist seems better than falling back on all products. This makes it easier for users to understand that something isn't working, while still giving them an idea of what this section should display.
This change also allowed to remove `.getFeaturedProducts()` from the `EcomAPI`, simplify the `FeaturedProductsSection` component by removing `useSWR` from it, and reduce the overall amount of code a little.
---
Skeletons:
> feat: remove fallback to all products in featured products section

- src/components/navigation-menu/navigation-menu.tsx
The className prop was lost in the [removing routes config PR](https://github.com/codux-templates/e-commerce-reclaim/pull/167).
> fix: Add class name to the About Us menu item

- .eslintrc.cjs
1. `react/jsx-no-target-blank` belongs in the React section rather than the TypeScript section.
2. `import/no-extraneous-dependencies` is redundant in the React section, since it's already specified in the TypeScript section and we're not using `js/jsx` in this project.
3. Added `@typescript-eslint/explicit-member-accessibility`
> infra: tweak .eslintrc

- src/components/spinner/spinner.module.scss
- src/components/spinner/spinner.tsx
I’d like to use the` <Spinner>` inside a button, but I need a few tweaks:
1. Allow to set the size in units other than pixels: `<Spinner size="1lh" />`.
2. Allow to pass a custom class name.
3. Avoid thinning the stroke at small sizes.
4. Automatically match light-on-dark and dark-on-light text.
https://github.com/user-attachments/assets/0bb665b2-9b91-4995-89aa-190a11a4461b
> refactor: spinner improvements

- lib/ecom/api.ts
- lib/ecom/wix-client-error.ts
`WixClient` throws errors with garbled messages, to fix them we have to chain `.catch(throwNormalizedWixClientError)` to each method call of `WixClient` inside of `EcomApi`. This is error-prone.
This PR introduces a helper function that iterates over all methods of `EcomApi` and wraps them with `normalizeWixClientError` automatically. The code is hacky, but it makes `EcomApi` methods nice and clean:
```ts
getCart() {
return wixClient.currentCart.getCurrentCart();
}
```
Other alternatives:
1. Add a try-catch inside of each `EcomApi` method:
```ts
async getCart() {
try {
return await wixClient.currentCart.getCurrentCart();
} catch (error) {
throw normalizeWixClientError(error);
}
}
```
2. Wrap each `EcomApi` method individually:
```ts
getCart: withNormalizedWixClientErrors(() => {
return …
```
> refactor: automatically normalize WixClient errors

- app/routes/cart/route.tsx
- lib/ecom/api.ts
- lib/ecom/hooks.ts
- lib/ecom/types.ts
- src/components/cart/cart-view/cart-view.tsx
- src/components/cart/cart.tsx
Fix the following issues:
1. An error message during checkout always displays as "checkout is not configured," regardless of the actual error.
2. After clicking "Checkout", no visual feedback is provided to the user for several seconds, until the redirect to the checkout page completes. I've disabled the button during checkout and added a spinner.
3. The thank you page URL is hardcoded in the `EcomApi`, even though it’s a user-defined route that should be configurable.
I've extracted `useCheckout` out of `useCart` since checkout now has required parameters, and I didn't want to always pass them to `useCart`:
```ts
const { checkout, isCheckoutInProgress } = useCheckout({
successUrl: '/thank-you',
cancelUrl: '/all-products',
onError: (error) => { ... }
});
```
Alternatively I could do it …
> fix(checkout): propagate correct error message and progress

- lib/ecom/api.ts
- lib/ecom/hooks.ts
- lib/ecom/types.ts
Migrated from error codes to exceptions:
* `EcomApi.getCart()`
* `EcomApi.getCartTotals()`
* `EcomApi.addToCart()`
* `EcomApi.removeFromCart()`
* `EcomApi.updateCartItemQuantity()`
The following two `WixClient` methods return an optional `Cart` object:
* `WixClient.currentCart.removeLineItemsFromCurrentCart()`
* `WixClient.currentCart.addToCurrentCart()`
I suspect the cart being optional is a lie, similar to `product._id` being optional. Even after removing the last item from the cart, the response still contains the cart object. I chose to ignore the type and treat the cart as always defined.
> refactor: migrate most of the cart API methods to exceptions

- src/styles/index.scss
update keyboard-focused item highlight color
before:
after:
> feat: improve keyboard-focused item highlight color

- src/components/applied-product-filters/applied-product-filters.tsx
- src/components/product-filters/product-filters.tsx
Range slider in product filters has step `any` because product price could be decimal. But we round it on change simulating integer step. This works well with mouse interactions. However, it doesn't work with a keyboard. The browser determines the delta when changing the value with a keyboard (when the step is `any`). Let's say it fires a change from `3` to `3.1`. And because we round it (`Math.floor`), nothing happens, the value remains `3`.
Having step `1` instead of `any` makes it way easier to handle.
The only downside: if the minimum price in a category is decimal, let's say `3.33`, a user can set min and max price filters both to `3`. This will show no results.
> fix: slider keyboard interaction in product filters

- src/components/avatar/avatar.tsx
without `crossOrigin="anonymous"` attribute, there are issues logged in dev tools saying that request is blocked according to CORB (not CORS) policy.
looks like when loading image, browser tries to send cookies (because user is logged in in gmail etc.) and this is not allowed for cross-origin requests
> fix: make avatar image cross-origin

- app/routes/_index/route.tsx
- src/components/featured-products-section/featured-products-section.module.scss
- src/components/featured-products-section/featured-products-section.tsx
- src/components/product-card/product-card.module.scss
- src/components/product-card/product-card.tsx
When the featured products section contains a single image, the image takes full page width, and because of 3/4 aspect ratio it's like two screens tall and huuuuge.
See here: https://github.com/wixplosives/codux/issues/23287
I've restricted the max width to 640px. Ought to be enough for anybody.
> feat: limit max width of cards in the featured products section

- app/root.tsx
- app/routes/product-details.$productSlug/route.tsx
- app/routes/products.$categorySlug/route.tsx
- app/routes/thank-you/route.tsx
- lib/utils/common.ts
- src/components/error-page/error-page.module.scss
- src/components/error-page/error-page.tsx
I want to reuse the same error boundary component across all routes for simplicity and consistency.
A route like `app/routes/products.$categorySlug/route.tsx` can simply include:
```ts
export { ErrorBoundary } from '~/src/components/error-page/error-page';
```
Apart from refactoring, there are a couple of functional changes in this PR:
For the 404 error, we had two custom messages: "Category Not Found" and "Product Not Found." I didn't feel the need to preserve these (though it would be easy to do), so now both display as "Page Not Found."
The root error boundary had a subtle issue: to display the site header, it rendered `<ContentWrapper>`, which rendered `<SiteWrapper>`, which rendered components like `<Cart>`, which can throw errors. So the error boundary component rendered something …
> feat: simplify error boundaries

- lib/ecom/wix-client-error.ts
- src/components/error-page/error-page.tsx
When a category is not found, the Wix Ecom API chooses seemingly at random between two responses with different error codes `404` and `"CATEGORY_NOT_FOUND"`:
```
{
"message": "Collection with slug baths was not found",
"details": {
"applicationError": {
"description": "Collection with slug baths was not found",
"code": 404
}
}
}
```
```
{
"message": "Collection with slug baths was not found for store 48734ffb-74ca-4fd1-b041-935e8ecaaad3: UNKNOWN",
"details": {
"applicationError": {
"description": "UNKNOWN",
"code": "CATEGORY_NOT_FOUND",
}
}
}
```
There's also a third code, `"NOT_FOUND"`, used by some other endpoints.
Also included in this PR a tweak to the workaround for Remix losing styles upon navigation from an error boundary. I've verified that the workaround is only needed in dev …
> fix: improve detection of 'category not found' error

- vite.config.ts
Fixes a dev-time issue observed consistently.
After a fresh (!) `node_modules` installation, and executing `npm run dev`, going to http://localhost:5173 and clicking on one of the categories causes a full reload with the message vite is optimizing `@radix-ui/react-select` and full reloads the page.
Vite tries to auto detect deps that require its optimization ahead of time, and for some reason it doesn't finds these from another route. Probably remix not configuring entrypoints correctly, or choosing to be lazy.
Using https://vite.dev/config/dep-optimization-options.html#optimizedeps-include we can avoid the first time reload.
> fix: ensure dev cold start doesn't reload

- app/routes/product-details.$productSlug/route.tsx
- app/routes/thank-you/route.module.scss
- app/routes/thank-you/route.tsx
- src/components/accordion/accordion.module.scss
- src/components/accordion/accordion.tsx
- src/components/order-summary/order-item/order-item.tsx
- src/components/order-summary/order-summary.module.scss
- src/components/order-summary/order-summary.tsx
- src/components/product-filters/product-filters.tsx
These changes needed for the `MyOrders` page that will come in the next PR
Accordion:
- added `initialOpenItemIndex` prop (currently first item is opened by default)
OrderSummary:
- UI tweaks (to be able to use the same component in the "Thank You" and "My Orders" pages)
- added "Price" label in the order item details
Updated `OrderSummary` on the Thank You page looks like this:
> feat: Tweaks to the Accordion and OrderSummary component

- _codux/board-templates/Default.board.tsx
- _codux/board-templates/DefaultBoard.board.tsx
- codux.config.json
https://github.com/user-attachments/assets/3c7faa40-cca7-4ff7-8bae-d4cf2bf9f8ec
If you use NewComponent dialog and want to see DefaultBoard template there you need to use `<ContentSlot/>`. [Read more](https://help.codux.com/kb/en/article/creating-board-templates#using-a-board-template-for-new-components)
> feat: add board template with component wrapper

- app/root.tsx
- env.d.ts
- src/wix/ecom/api.ts
In `env.d.ts`, we had a reference to a non-existent `ClientENV` type:
```ts
declare interface Window {
ENV: ClientENV;
}
```
I've removed `window.ENV`, made `WIX_CLIENT_ID` a local variable in `ecom/api.ts`, and exported `getWixClientId()` and `setWixClientId()` to access it.
> refactor: move WIX_CLIENT_ID from global scope to module scope

- app/root.tsx
- src/components/navigation-progress/navigation-progress.module.scss
- src/components/navigation-progress/navigation-progress.tsx
- src/styles/colors.scss
A little progress bar at the top of the page that is displayed during client-side navigation:
https://github.com/user-attachments/assets/770b3350-7fee-4eb4-a1b8-e0b113e6436f
> feat: page loading indicator for client-side navigation

- app/routes/products.$categorySlug/route.tsx
- src/wix/products/use-products-page-results.ts
When clicking 'Load more' on the products page, show a toast instead of an alert in case of an error response.
> feat: use a toast instead of an alert on the browse products page

- vite.config.ts
remix warns about these today, as they are going to change the behavior in remix@3 / react-router@7.
by enabling the flags, we turn on the new behavior today.
everything seems to work pretty snappy from my own testing.
this also fixes all the warnings during `npm run dev` since the latest version of remix.
> feat: enable future flags for forward compatibility

- src/wix/ecom/api.ts
In #226, I changed `process.env.WIX_CLIENT_ID` to `globalThis.process.env.WIX_CLIENT_ID` to avoid the clunky `typeof process !== 'undefined'`.
In Node, they're interchangable because of course they are. But when Codux copies `process` into the preview environment, it somehow breaks access through `globalThis`.
Anyway, I've changed it back.
> fix: correctly read WIX_CLIENT_ID from the .env file when running in Codux

- src/components/applied-product-filters/applied-product-filters.tsx
- src/components/product-filters/price-filter.tsx
- src/wix/utils/align-range.ts
When the price range is large, it's difficult to adjust the slider via keyboard because `step = 1`:
https://github.com/user-attachments/assets/651493d3-3d63-4845-9d94-230b28746bbf
A quick fix could look like this:
```ts
const step = maxAvailablePrice > 500 ? 10 : 1;
```
But this wouldn't solve the issue for prices above 10 000, and would break alignment of range bounds with the step size.
We should have probably ignored this entire "problem", but I couldn't let practicality stand in the way of solving a nice math puzzle. So I've created a function `alignRangeToNiceStep` that makes things nice:
https://github.com/user-attachments/assets/71d97c71-1eeb-424a-a99d-602d21f720f0
The implementation could have been condensed into 10-15 lines, but I went for readability.
> feat: auto-adjust slider step size to price range in price filter

- src/wix/ecom/session.ts
**Summary:**
This PR renews the Wix authentication token and saves it in the session if it has expired. If the renewal process fails, it logs the user out by generating a new visitor auth token.
**Frontend Considerations:**
The frontend side token refresh is not addressed in this PR due to the following reasons:
- In order to token expire, a user would need to leave the page inactive for 4 hours (the access token’s lifetime), then resume interaction without a full page reload or opening a new tab.
- Addressing this would significantly increase template code complexity.
- Additionally, the Wix SDK automatically updates expired tokens before each request. While the updated token is not preserved, the SDK will continue to fetch a new token before every request if the token expires. This …
> feat: renew wix auth token

- app/routes/cart/route.module.scss
- app/routes/cart/route.tsx
On the template it is shown the name of shipping region.
User can manage shipping regions in Wix Studio backoffice:
> Fix: make shipping info dynamic

- app/routes/cart/route.tsx
I there is only one shipping region (for. e.g. Poland) and user is located in another place (for e.g. Ukraine) then delivery price will be shown FREE, but actually it's not possible to deliver to Ukraine.
I hide delivery information if shipping region is undefined.
> fix: don't show delivery price if no shipping region is detected

- src/components/avatar/avatar.module.scss
- src/components/cart/cart-item/cart-item.module.scss
- src/components/product-option/product-option.module.scss
- src/components/select/select.module.scss
- src/styles/colors.scss
- src/styles/global.scss
- src/styles/utils.scss
Allow users to easily customize the `<body>` background and text colors through the global variables panel, as the style panel currently does not support editing the `<body>`.
> feat: add CSS vars for page background and text color

- src/components/avatar/avatar.tsx
- src/components/product-card/product-card.tsx
- src/components/visual-effects/background-parallax.tsx
> fix: add @format comment before image url fields to allow using Wix Media Manager

- src/components/header/header.module.scss
- src/components/search-input/search-input.module.scss
- src/components/search-input/search-input.tsx
- src/components/user-menu/user-menu.module.scss
- src/components/user-menu/user-menu.tsx
On mobile, the icons in the search input were disappearing, "Log in" was wrapping to the next line, the user icon and the hamburger icons were shrinking.
---
Tweaks to the search input:
* Moved the `<label>` inside the `<Form>`.
* Removed `memo` since the props weren't memoized anyway, and the component isn't on the hot path. Maybe we should memoize the `<Header>` component.
* Simplified code for `clear` and `submit`.
* Fixed the font size (it was off by one pixel).
* Tried to stick with `em` units, but getting the sizes right, rather than just approximately right, turned out to be too much of a hassle. You have to keep track of the current font size and end up with awkward values like `0.571em`. Ain't nobody got time for that.
* Removed browser's default `min-width` and `padding` from …
> fix: header styles on mobile

- app/root.tsx
Due to a bug in Codux, the App component appears four times in the element tree. This happens when the component doesn't have a single root DOM element.
https://github.com/wixplosives/codux/issues/24380
https://github.com/wixplosives/codux/issues/21951
> fix: workaround for Codux showing 4 instances of the App component in the element tree

- app/routes/product-details.$productSlug/route.tsx
During client-side navigation between product pages, we need to ensure that React state (such as selected product options, quantity, selected photo) is not retained.
> fix: reset selected options and quantity when navigating between products
